module.exports = {
    promptInput: '',
    printBuffer: ['You\'re soaked. Have been for hours. There\'s lightning, but you can\'t hear the thunder over the constant beat of the rain on the ocean. In the flashes you can see the big houses on Ingrete tumbling down the hillside. Must have been a mudslide. Chop is lapping onto the dock and washing over your ankles. You came to Ricken\'s because you\'ve already expended your other options. He can get you out and he wants what you\'ve got.'],
    action: '',
    location: 'RICKENS_DOOR',
    Inventory: [],
    maxInventorySize: 4,
    mapPosition: {
        'y': 0,
        'x': 8,
    },
    mapGrid: [],
    selfIcon: '_',
    status: [],
    blood: 10,
    bloodBar: [],
    stamina: 10,
    staminaBar: [],
    mobility: 10,
    mobilityBar: [],
    temperature: 5,
    temperatureBar: [],
    thirst: 10,
    thirstBar: [],
    hunger: 10,
    hungerBar: [],
    time: 65,
    hours: 0,
    dynamicLocations: []
}

